import "~/styles/globals.css";
import { TopNav } from "./_components/topnav";
import { GeistSans } from "geist/font/sans";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Jamz Along",
  description: "Generated by create-t3-app",
  icons: [
    {
      rel: "icon",
      url: "https://i.pngimg.me/thumb/f/720/m2i8G6K9b1m2d3Z5.jpg",
    },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className={`font-sans ${inter.variable} flex flex-col gap-4`}>
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
